### ISSUE TITLE
Rows and Columns both set to n

### ISSUE THREAD

**Issue by rhysnewell** [preiter93/ndfft_test#1]
Hello,

Thanks for throwing this together. It's been super helpful to go through as I have had trouble understanding how best to use rustfft with multidimensional arrays. I do have a question about this line of code: https://github.com/preiter93/ndfft_test/blob/master/src/ndfft_with_transpose.rs#L21

For `oop_transpose` function you've set the rows and columns to be both equal to `n`. Should the columns instead be set to `m` or am I misunderstanding the use of this function?

Cheers,
Rhys

**Comment by preiter93** [comment]
Hey, 
glad it's of someones help :) 

Yes, you are right, that should be changed, I will do it tomorrow. 

If you are interested in the transpose method, 
you can also  look into https://docs.rs/transpose/latest/transpose/ 
for out-of-place transforms. It should be around the same performance as in this test
